#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=14

cd "$(dirname "$0")/.."
ENV_FILE="backend/.env"
LOCAL_DATABASE_URL="postgresql://postgres:postgres@127.0.0.1:54422/postgres"

# chat_id_from_updates TOKEN prints the chat id of the newest private message to that bot.
chat_id_from_updates() {
  curl -fsS "https://api.telegram.org/bot$1/getUpdates" | python3 -c '
import json, sys
updates = json.load(sys.stdin).get("result", [])
chats = [u["message"]["chat"]["id"] for u in updates if "message" in u]
print(chats[-1] if chats else "")'
}

# vercel_env NAME VALUE sets a Production env var on the linked Vercel project.
vercel_env() {
  (cd backend && vercel env rm "$1" production -y >/dev/null 2>&1 || true)
  if (cd backend && printf '%s' "$2" | vercel env add "$1" production >/dev/null 2>&1); then
    printf '  %s✓ set%s Vercel env %s (production)\n' "$GREEN" "$RESET" "$1"
  else
    SKIPPED+=("Vercel env $1 (run: cd backend && vercel env add $1 production)")
    warn "couldn't set Vercel env $1; set it by hand later"
  fi
}

banner "Hybrid Athlete Coach: accounts, deploy and first message"

stage "Supabase: create the project"
say "The database, the agent's memory and (later) the dashboard login all live here."
open_url "https://supabase.com/dashboard/new"
step "Sign in (GitHub works), pick your organization, then New project."
step "Name it 'hybrid-athlete-coach', region: Asia-Pacific (Sydney) ap-southeast-2."
step "Generate a strong database password and save it in your password manager."
step "Click Create new project and wait until the dashboard shows it as healthy."
pause "Press Enter once the project is ready."

stage "Supabase: connection string"
say "The backend runs on Vercel functions, so it connects through the transaction pooler."
step "In the project, click Connect (top bar)."
step "Under Connection String, choose the Transaction pooler entry (port 6543)."
step "Copy the URI and replace [YOUR-PASSWORD] with the password you saved."
note "It looks like postgresql://postgres.<ref>:<password>@aws-0-ap-southeast-2.pooler.supabase.com:6543/postgres"
note "Saved as PROD_DATABASE_URL; your local .env keeps pointing at the local database."
ask_secret PROD_DATABASE_URL "Paste the full URI (hidden):"
write_env PROD_DATABASE_URL "$PROD_DATABASE_URL"
write_env COACH_DATABASE_URL "$LOCAL_DATABASE_URL"

stage "Telegram: dev bot"
say "The dev bot is for local long polling; it never gets a webhook."
open_url "https://t.me/BotFather"
step "Send /newbot to BotFather."
step "Display name: 'Coach Dev'. Username: something ending in _dev_bot, e.g. <you>_coach_dev_bot."
step "BotFather replies with an HTTP API token. Copy it."
ask_secret COACH_TELEGRAM_BOT_TOKEN "Paste the DEV bot token (hidden):"
write_env COACH_TELEGRAM_BOT_TOKEN "$COACH_TELEGRAM_BOT_TOKEN"

stage "Telegram: production bot"
say "The production bot is the one Vercel serves through the webhook."
step "In BotFather, send /newbot again."
step "Display name: 'Coach'. Username ending in _bot, e.g. <you>_coach_bot."
step "Copy its token."
note "Saved as PROD_TELEGRAM_BOT_TOKEN (no COACH_ prefix) so local runs keep using the dev bot."
ask_secret PROD_TELEGRAM_BOT_TOKEN "Paste the PRODUCTION bot token (hidden):"
write_env PROD_TELEGRAM_BOT_TOKEN "$PROD_TELEGRAM_BOT_TOKEN"

stage "Telegram: your chat id"
say "Only your chat may talk to the coach, so we need its id."
step "Open your DEV bot in Telegram, press Start, and send it any message (e.g. 'hi')."
pause "Press Enter once you've sent it."
CHAT_ID=$(chat_id_from_updates "$COACH_TELEGRAM_BOT_TOKEN" || true)
if [[ -z "$CHAT_ID" ]]; then
  warn "No message found yet. Send another message to the dev bot."
  pause "Press Enter to try again."
  CHAT_ID=$(chat_id_from_updates "$COACH_TELEGRAM_BOT_TOKEN" || true)
fi
if [[ -z "$CHAT_ID" ]]; then
  ask CHAT_ID "Couldn't read it automatically. Enter your numeric chat id:"
fi
say "Your chat id is $CHAT_ID."
write_env COACH_TELEGRAM_ALLOWED_CHAT_IDS "[$CHAT_ID]"

stage "Webhook secret"
say "Telegram will send this secret with every webhook call; the backend rejects anything else."
if [[ -n "$(_existing COACH_TELEGRAM_WEBHOOK_SECRET || true)" ]]; then
  COACH_TELEGRAM_WEBHOOK_SECRET=$(_existing COACH_TELEGRAM_WEBHOOK_SECRET)
  note "Keeping the secret already in $ENV_FILE."
else
  COACH_TELEGRAM_WEBHOOK_SECRET=$(openssl rand -hex 32)
  write_env COACH_TELEGRAM_WEBHOOK_SECRET "$COACH_TELEGRAM_WEBHOOK_SECRET"
fi
pause

stage "Anthropic: API key and spend limit"
open_url "https://console.anthropic.com/settings/keys"
step "Create Key, name it 'hybrid-athlete-coach', copy it (shown once)."
ask_secret COACH_ANTHROPIC_API_KEY "Paste the API key (hidden):"
write_env COACH_ANTHROPIC_API_KEY "$COACH_ANTHROPIC_API_KEY"
open_url "https://console.anthropic.com/settings/limits"
step "Set a monthly spend limit of \$10 for this workspace."
note "If the page differs, look for Limits or Spend limits under Settings."
pause "Press Enter once the limit is set."

stage "Database: schema and your athlete, production and local"
say "Creates every table, the agent's checkpoint tables, and row-level security."
ask ATHLETE_NAME "Your name, as the coach should call you:"
say "Production (Supabase):"
if ! (cd backend && COACH_DATABASE_URL="$PROD_DATABASE_URL" uv run coach migrate); then
  warn "Migration failed. If the error mentions CONCURRENTLY or prepared statements,"
  warn "re-run with the Session pooler URI (port 5432) from the same Connect dialog."
  exit 1
fi
(cd backend && COACH_DATABASE_URL="$PROD_DATABASE_URL" \
  uv run coach add-athlete --name "$ATHLETE_NAME" --chat-id "$CHAT_ID")
say "Local (Docker), so local runs never touch your real coach memory:"
supabase db start
(cd backend && uv run coach migrate)
(cd backend && uv run coach add-athlete --name "$ATHLETE_NAME" --chat-id "$CHAT_ID")
pause

stage "Local check with the dev bot"
say "Runs the bot on this machine against the local database. Watch for a reply in Telegram."
step "When it says 'Long polling', send the DEV bot: how much did I train this week?"
step "Expect a short reply saying nothing is logged yet. Then press Ctrl-C here."
pause "Press Enter to start polling."
# A handler (not an ignore) so Ctrl-C stops the poller but not this wizard.
trap 'true' INT
(cd backend && uv run coach poll) || true
trap - INT
confirm "Did the dev bot reply?" || { warn "Fix the local run before deploying (check the log above)."; exit 1; }

stage "Vercel: link the backend"
say "The backend becomes its own Vercel project with root directory backend/."
(cd backend && vercel whoami >/dev/null 2>&1) || (cd backend && vercel login)
step "Answer the prompts: set up a new project, name it 'hybrid-athlete-coach-backend'."
step "When asked for the code directory, keep ./ (you are already in backend/)."
(cd backend && vercel link)
pause

stage "Vercel: production environment variables"
say "Production values: the Supabase database and the PRODUCTION bot token."
vercel_env COACH_DATABASE_URL "$PROD_DATABASE_URL"
vercel_env COACH_TELEGRAM_BOT_TOKEN "$PROD_TELEGRAM_BOT_TOKEN"
vercel_env COACH_TELEGRAM_WEBHOOK_SECRET "$COACH_TELEGRAM_WEBHOOK_SECRET"
vercel_env COACH_TELEGRAM_ALLOWED_CHAT_IDS "[$CHAT_ID]"
vercel_env COACH_ANTHROPIC_API_KEY "$COACH_ANTHROPIC_API_KEY"
pause

stage "Vercel: deploy to production"
confirm "Deploy the backend to production now?" || { warn "Stopped before deploying."; exit 1; }
(cd backend && vercel deploy --prod)
step "Copy the Production domain from the output above (e.g. hybrid-athlete-coach-backend.vercel.app)."
ask PROD_DOMAIN "Production domain (without https://):"
PROD_DOMAIN="${PROD_DOMAIN#https://}"; PROD_DOMAIN="${PROD_DOMAIN%/}"
write_env PROD_DOMAIN "$PROD_DOMAIN"
if curl -fsS "https://$PROD_DOMAIN/health" | grep -q '"ok"'; then
  say "Health check passed."
else
  warn "https://$PROD_DOMAIN/health did not answer ok. Check the deployment logs in Vercel."
  warn "If the build log shows an entrypoint/import error for coach.main:app, tell your agent."
  exit 1
fi
pause

stage "Telegram: point the production bot at Vercel"
confirm "Set the production bot's webhook to https://$PROD_DOMAIN/telegram?" || exit 1
(cd backend && COACH_TELEGRAM_BOT_TOKEN="$PROD_TELEGRAM_BOT_TOKEN" \
  uv run coach set-webhook --url "https://$PROD_DOMAIN/telegram")
pause

stage "End-to-end check"
step "Send the PRODUCTION bot: how much did I train this week?"
pause "Press Enter after it replies."
say "Latest agent turn (error should be empty):"
psql "$PROD_DATABASE_URL" -c "select trigger, model, input_tokens, output_tokens, latency_ms, error from agent_runs order by created_at desc limit 1" \
  || warn "psql could not connect; check the turn in the Supabase table editor instead."
step "Optional: from another Telegram account, message the production bot. It must not reply."
pause

finish
